import os

def build_markdown_report(records):
    """Membuat laporan dalam format Markdown."""
    lines = [
        "# Rekap Nilai Mahasiswa\n",
        "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |",
        "|---|---|---:|---:|:---:|",
    ]
    for r in records:
        lines.append(f"| {r['nim']} | {r['nama']} | {r['hadir']:.1f} | {r['akhir']:.2f} | {r['predikat']} |")
    lines.append("\nGenerated by student_performance_tracker")
    return "\n".join(lines)


def build_html_report(records):
    """Membuat laporan HTML dengan warna berdasarkan predikat."""
    color_map = {
        "A": "#4CAF50",   # hijau
        "B": "#8BC34A",
        "C": "#FFC107",
        "D": "#FF9800",
        "E": "#F44336",   # merah
    }

    rows = ""
    for r in records:
        color = color_map.get(r["predikat"], "#FFFFFF")
        rows += f"""
        <tr style='background-color:{color}33'>
            <td>{r['nim']}</td>
            <td>{r['nama']}</td>
            <td style='text-align:right'>{r['hadir']:.1f}%</td>
            <td style='text-align:right'>{r['akhir']:.2f}</td>
            <td style='text-align:center'>{r['predikat']}</td>
        </tr>"""

    html = f"""
    <html>
    <head>
        <meta charset="utf-8">
        <title>Rekap Nilai Mahasiswa</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; }}
            table {{ border-collapse: collapse; width: 100%; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; }}
            th {{ background-color: #2196F3; color: white; }}
        </style>
    </head>
    <body>
        <h2>Rekap Nilai Mahasiswa</h2>
        <table>
            <tr>
                <th>NIM</th><th>Nama</th><th>Hadir (%)</th><th>Nilai Akhir</th><th>Predikat</th>
            </tr>
            {rows}
        </table>
        <p><i>Generated by student_performance_tracker</i></p>
    </body>
    </html>
    """
    return html


def save_text(path, content):
    """Menyimpan teks ke file (otomatis buat folder)."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
